### PR TITLE
Add version pinning

### PR DESCRIPTION
**Pull request by roguh**

### CODE REVIEW

**Comment by kungfuchicken** [comment]
Task linked: [CU-2nq3bda [Logging Utilities Library] Add version pinning to this library's dependencies](https://app.clickup.com/t/2nq3bda)

**Review by nicoLedesma — APPROVED** [review]
OK.

**Review by dino-powerflex — COMMENTED** [review]
LGTM. Question: why are some dependencies managed via requirements.txt and others via setup.py?

**Comment by roguh** [comment]
`requirements_dev.txt` contains dependencies for local development, and the `setup.py` file contains requirements for the Python package. We organize most of our Python repos as Python packages, so that's why you'll see dependency management done through `setup.py`

**Pull request merged**
